<!-- id="co-billing-form" -->
<div id="form-validate-address-add-popup">
<form method="post" id="form-validate-address-add">
<fieldset>
 
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
    <input type="hidden" name="id" id="entity_id" value="" />
        <h2 class="legend" id="add-new-address-legend"><?php echo $this->__('Add New Address') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <li class="wide">
                <label for="company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                    </div>
                </div>
                <div class="field">
                    <label for="fax"><?php echo $this->__('Fax') ?></label>
                    <div class="input-box">
                        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <li class="wide">
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
        <?php endfor; ?>
            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <li class="wide">
                <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                <div class="input-box">
                    <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </li>
            <?php endif; ?>
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            jQuery('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif; ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-address" id="btn-save-address"  type="submit" title="<?php echo $this->__('Save Address') ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
     
</fieldset>
</form>
</div>
<script type="text/javascript">
//<![CDATA[

    var dataForm = new VarienForm('form-validate-address-add', true);
    var regionUpdate = new RegionUpdater('country_id', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

    jQuery(document).ready(function(e){
        jQuery("#form-validate-address-add").submit (function(e){
            e.preventDefault();
            var that = jQuery("#btn-save-address");
            if(dataForm.validator.validate()){
                var data = Form.serialize("form-validate-address-add");
                jQuery.ajax({
                    url:"http://127.0.0.1/magento1_test/checkout/address/save",
                    type:"POST",
                    dataType:"json",
                    data:data,
                    beforeSend:function(){
                       $(that).attr("disabled","disabled")  
                    },
                    success:function(r){
                       $(that).removeAttr("disabled")  
                       jQuery("#form-validate-address-list-div").html(r.html)
                       emptyForm()
                    }
                })
            }
        })

        /**
         * Edit  
         */    
        /* Delete Address */
        jQuery("#form-validate-address-list-div").delegate(".edit-address","click",function(e){
            e.preventDefault();
            var that = jQuery(this);
            var id = jQuery(that).data("id");
            jQuery.ajax({
                url:"http://127.0.0.1/magento1_test/checkout/address/get",
                type:"GET",
                dataType:"json",
                data:{id:id},
                beforeSend:function(){
                   jQuery("#add-new-address-legend").text("Edit Address")
                },
                success:function(r){

                   if(r.status=="success"){
                         var data = r.data;             
                         jQuery("#entity_id").val(data.entity_id);
                         jQuery("#firstname").val(data.firstname);
                         jQuery("#lastname").val(data.lastname);
                         jQuery("#company").val(data.company);
                         jQuery("#city").val(data.city);
                         jQuery("#country_id").val(data.country_id);
                         jQuery("#region").val(data.region);
                         jQuery("#zip").val(data.postcode);
                         jQuery("#telephone").val(data.telephone);
                         jQuery("#fax").val(data.fax);
                         jQuery("#region_id").val(data.region_id);
                         jQuery("#street_1").val(data.street[0]);
                         jQuery("#street_2").val(data.street[1]); 
                         regionUpdate.update()
                   }
                }
            })                    
        })      
             
        /* Delete Address */
        jQuery(".delete-address").click(function(e){
            e.preventDefault();
            var that = jQuery(this);
            var id = jQuery(that).data("id");
            jQuery.ajax({
                url:"http://127.0.0.1/magento1_test/checkout/address/delete",
                type:"POST",
                dataType:"json",
                data:{id:id},
                beforeSend:function(){

                },
                success:function(r){
                   if(r.status=="success"){
                     jQuery("#form-validate-address-list-div").html(r.html) 
                     jQuery(that).closest("li").remove()
                   }
                }
            })                    
        })
     
         
        jQuery("#add-new-address").click(function(e){
            e.preventDefault();
            emptyForm();
            
            jQuery.magnificPopup.open({
                items: {
                    src: "#form-validate-address-add-popup"
                },
                type: 'inline',
                removalDelay: 300,
                closeOnBgClick: true,
                preloader: true,
                tLoading: '',
                callbacks: {                     
                    open: function () {},
                    beforeClose: function () {},
                    close: function () {},                    
                }
            });
        })
 
    })

   function emptyForm()
    {
       jQuery("#entity_id").val('');
       jQuery("#firstname").val('');
       jQuery("#lastname").val('');
       jQuery("#company").val('');
       jQuery("#city").val('');
       jQuery("#country_id").val('');
       jQuery("#region").val('');
       jQuery("#zip").val('');
       jQuery("#telephone").val('');
       jQuery("#fax").val('');
       jQuery("#region_id").val('');
       jQuery("#street_1").val('');
       jQuery("#street_2").val(''); 
       jQuery("#add-new-address-legend").text("Add New Address")
    } 
//]]>
</script> 
